### ISSUE TITLE
tinycuda error 

### ISSUE THREAD

**Issue by githubLeoliu** [autonomousvision/sdfstudio#33]
I installed the tinycuda with the command

`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` 

When I try `import  tinycudann`, I got this error

`Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/leo/anaconda3/envs/sdfstudio/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module> from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding File "/home/leo/anaconda3/envs/sdfstudio/lib/python3.10/site-packages/tinycudann/modules.py", line 50, in <module> _C = importlib.import_module(f"tinycudann_bindings._{cc}_C") File "/home/leo/anaconda3/envs/sdfstudio/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: /home/leo/anaconda3/envs/sdfstudio/lib/python3.10/site-packages/tinycudann_bindings/_61_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE

I tired this in following environment:`
Ubuntu 22.04
python 10
pytroch 1.12.1+cu113

**Comment by Dawars** [comment]
Try installing via `python -m pip ...`  maybe pip is installing to a different environment

**Comment by githubLeoliu** [comment]
I tried `python -m pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch` still does not work. 

how suppose I check if tinycudann is installed in correct environment explicitly?

**Comment by Dawars** [comment]
Is there anything in this directory?
`/home/leo/anaconda3/envs/sdfstudio/lib/python3.10/site-packages/tinycudann_bindings/`

Search your computer for a file named _**_C.cpython-310-x86_64-linux-gnu.so

Or try to create a new env and paste here the output of tinycudann installation.

**Comment by githubLeoliu** [comment]
`leo@leo-Alienware-15-R3:~/anaconda3/envs/sdfstudio/lib/python3.10/site-packages/tinycudann_bindings$ ls
_61_C.cpython-310-x86_64-linux-gnu.so`

the `_**_C.cpython-310-x86_64-linux-gnu.so` file is under the correct directory in my environment

**Comment by Dawars** [comment]
You are right, I missed this part:
`undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE`

What GPU do you have? Maybe this operation is not supported for gpu capability 6.1

**Comment by githubLeoliu** [comment]
I have a GTX 1060, I also post an issue on tiny-cuda-nn repo.

**Comment by qsun1** [comment]
## Local implementation
I got such dependecies: torch==1.12.1+cu113 and corresponding torchvision and torchaudio packages.(nvcc --version->11.3 in my case)
Then executing the following codes
```
$ git clone --recursive https://github.com/nvlabs/tiny-cuda-nn
$ cd tiny-cuda-nn
```
and it works!

**Comment by Dawn11041107** [comment]
I tried a lots, and found the following methods works for me:

1.Clone the project first:
```
git clone --recursive https://github.com/nvlabs/tiny-cuda-nn
```

2.Go into the project folder:
 ```
cd tiny-cuda-nn    
```

3.Then build the project with cmake:
  ```
tiny-cuda-nn$ cmake . -B build
tiny-cuda-nn$ cmake --build build --config RelWithDebInfo -j
```

4.Enter the folder where setup.py is located:
 ```
cd tiny-cuda-nn/bindings/torch
```

5.Just run setup.py:
  ```
python setup.py install
 ```
6.If the following code does not report an error, it means that tinycudann is installed successfully!
  ```
python
  >>> import tinycudann as tcnn
```
Then you can run according to the command provided by the author：
` git clone ...`
Hope it will help you!希望可以帮到大家^^有问题可以给我留言

**Comment by GARV-k** [comment]
@githubLeoliu got any fix for this finally ? 
I am getting the same error.
